# This workflow is useful if you want to automate the processs of:
#
# a) creating a new prelease when you push a new tag with with "v" prefix (version).
#
#    this type of prerelease is meant to be used for production, alpha, beta, rc, etc type of releases.
#    after the prerelease is created, you need to make your needed changes on the release page at 
#    Github UI and publish your release.
#
# b) creating/updating the "latest" prerelease when you push to your default branch.
#
#    this type of prelease is useful make your bleeding-edge binaries avaiable to advanced users.
on: push

jobs:
  might_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Prepare Release Variables 
        id: vars
        uses: tendermint/starport/actions/release/vars@feat/action2

      - name: Issue Release Assets 
        uses: tendermint/starport/actions/cli@feat/action2
        if: ${{ steps.vars.outputs.should_release == 'true' }}
        with:
          args: build --release --release.prefix ${{ steps.vars.outputs.tarball_prefix }} -t linux:amd64 -t linux:arm64 -t darwin:amd64 -t darwin:arm64

      - name: Delete the "latest" Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0 
        if: ${{ steps.vars.outputs.is_release_type_latest == 'true' }}
        with:
          tag_name: ${{ steps.vars.outputs.tag_name }}
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish the Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.vars.outputs.should_release == 'true' }}
        with:
          tag_name: ${{ steps.vars.outputs.tag_name }}
          files: release/*
          prerelease: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
